### ISSUE TITLE
404 Not Found when coursework contains a project

### ISSUE THREAD

**Issue by awdavis** [camann9/MimirDownloader#1]
Stack trace:
```
Loading assignment Lab 1 (1d41e0f1-5a86-4009-b04b-bd406cf5066d)
Exception in thread "main" com.google.api.client.http.HttpResponseException: 404 Not Found
{"status":404,"error":"Not Found"}
	at com.google.api.client.http.HttpRequest.execute(HttpRequest.java:1070)
	at com.amann.mimir_downloader.Networking.executeAuthedRequest(Networking.java:80)
	at com.amann.mimir_downloader.AssignmentLoader.loadAssignment(AssignmentLoader.java:43)
	at com.amann.mimir_downloader.CourseLoader.loadCourse(CourseLoader.java:31)
	at com.amann.mimir_downloader.MimirDownloader.main(MimirDownloader.java:63)
```

The JSON for Lab 1 is as follows:
```
{"id":"1d41e0f1-5a86-4009-b04b-bd406cf5066d","name":"Lab 1","workType":"project","openDate":"2018-08-21T19:20:00.000Z"}
```

It appears that https://github.com/camann9/MimirDownloader/blob/master/mimir-downloader/src/main/java/com/amann/mimir_downloader/data/json/RawCourse.java#L10 needs to filter on workType = assignment.

**Comment by camann9** [comment]
Fixed in c0df711d0a6f6744253916b1d862a7e9a14ea8cd
